### ISSUE TITLE
"#element" selector seems to be ignored

### ISSUE THREAD

**Issue by ghost** [LukyVj/accecss#15]
Hi, 
First of all great job i love it!
I am trying to build a little tool to allow the designers I work with to test quickly their design against the different filters.

I have something like that on my .scss

```
@include accecss(
  "#imgZone",
  false,
  false,
  protanopia
);
```

it works, but the effects gets applied to the all page and not only to the #imgZone div and it's children's.

in fact no mater what I put as an argument for "element" the css will always output  a "html body" selector with my filter. 

Is this an expected behavior or am I missing something? 

Thanks

**Comment by LukyVj** [comment]
Hi @LorenzoPirondini,

Thank you for opening the issue, I'm currently trying to make a test case to get what happen with your error.

But first let me ask you some things, just to be sure :) 
- Is the `#imgZone` already present in the page when you load it, or is it appended somehow after the initial pageload ?  
- Are you doing advanced css transform on this element ? Such as `translateZ()` or similar transform ? 

I'm still trying to reproduce the error, I get back to you once I found something to make it work. 

Thank you again.

**Comment by ghost** [comment]
Hi,
 the div is present on page load, and have some css transform applied on user interaction. 

The problem seems to be when compiling the scss. 

the following :

```
@include accecss(
  "#imgZone",
  false,
  false,
  protanopia
);
```

always output: 

```
html body {
  filter: url("../css//filters.svg#protanopia") grayscale(0) !important; }
/*
CSS accecss : FALSE
*/
```

it seems it always triggers the if statement on line 198, i changed `html body` to  `#{$element}` to make it work temporarily.

**Comment by LukyVj** [comment]
Ok, I got the problem now. 
If you can wait till this early afternoon, I will fix this ! 

I had the same problem yesterday. Thank you for pointing this out @LorenzoPirondini

**Comment by ghost** [comment]
No problem I have that quick fix L199 in the meantime.
Thanks

**Comment by LukyVj** [comment]
Hi @LorenzoPirondini, 

I created a fix, reworking the mixin a little bit. 
You can find the new code here : https://github.com/LukyVj/accecss/blob/gh-pages/css/accecss.scss

Could you try it and tell me if it suits to your expectations ? 
It seems to work pretty good on my tests. 

Let me know,
Thanks !

**Comment by LukyVj** [comment]
@LorenzoPirondini Is it working now ? 
Let me know. 

Regards.

**Comment by ghost** [comment]
Hi @LukyVj ,
Sorry for the delay, and thanks for the fix everything work as expected now, I tried passing various types of css selectors in the element argument and it behaves as expected. 

Thanks.
